export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FALIUR = "FETCH_PRODUCTS_FALIUR";

export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";

export const INCREASE_TO_CART = "INCREASE_TO_CART";
export const DECRESE_TO_CART = "DECRESE_TO_CART";

export const SET_SIZE = "SET_SIZE";


