export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FALIUR = "FETCH_PRODUCTS_FALIUR";

export const FETCH_MOBILE_REQUEST = "FETCH_MOBILE_REQUEST";
export const FETCH_MOBILE_SUCCESS = "FETCH_MOBILE_SUCCESS";
export const FETCH_MOBILE_FALIUR = "FETCH_MOBILE_FALIUR";

export const FETCH_MENS_WEAR_REQUEST = "FETCH_MENS_WEAR_REQUEST";
export const FETCH_MENS_WEAR_SUCCESS = "FETCH_MENS_WEAR_SUCCESS";
export const FETCH_MENS_WEAR_FALIUR = "FETCH_MENS_WEAR_FALIUR";

export const FETCH_KIDS_WEAR_REQUEST = "FETCH_KIDS_WEAR_REQUEST";
export const FETCH_KIDS_WEAR_SUCCESS = "FETCH_KIDS_WEAR_SUCCESS";
export const FETCH_KIDS_WEAR_FALIUR = "FETCH_KIDS_WEAR_FALIUR";

export const FETCH_HOME_DECOR_REQUEST = "FETCH_HOME_DECOR_REQUEST";
export const FETCH_HOME_DECOR_SUCCESS = "FETCH_HOME_DECOR_SUCCESS";
export const FETCH_HOME_DECOR_FALIUR = "FETCH_HOME_DECOR_FALIUR";

export const FETCH_BEAUTY_REQUEST = "FETCH_BEAUTY_REQUEST";
export const FETCH_BEAUTY_SUCCESS = "FETCH_BEAUTY_SUCCESS";
export const FETCH_BEAUTY_FALIUR = "FETCH_BEAUTY_FALIUR";

export const FETCH_ELECTRONICS_REQUEST = "FETCH_ELECTRONICS_REQUEST";
export const FETCH_ELECTRONICS_SUCCESS = "FETCH_ELECTRONICS_SUCCESS";
export const FETCH_ELECTRONICS_FALIUR = "FETCH_ELECTRONICS_FALIUR";