export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FALIUR = "FETCH_PRODUCTS_FALIUR";

export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
